# Generated by Django 6.0.6 on 2026-06-30 19:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_deliveryevent_route_corridor_km'),
        ('notifications', '0001_initial'),
        ('parcels', '0003_alter_parcel_area_sq_m_alter_parcel_location'),
        ('stands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. Home, Work, Grandma's village", max_length=60)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_zones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', django.contrib.gis.db.models.fields.PointField(help_text="Snapshot of the channel's location at submit time", srid=4326)),
                ('radius_km', models.FloatField(default=3)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent')], default='pending', max_length=10)),
                ('matched_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('delivery_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_requests', to='delivery.deliveryevent')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_requests', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_requests', to='parcels.parcel')),
                ('stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_requests', to='stands.stand')),
            ],
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_json', models.TextField(help_text='Raw PushSubscription JSON from the browser')),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_interests', to=settings.AUTH_USER_MODEL)),
                ('delivery_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='delivery.deliveryevent')),
            ],
            options={
                'unique_together': {('buyer', 'delivery_event')},
            },
        ),
    ]
