# Generated by Django 6.0.6 on 2026-06-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alertzone_notificationrequest_webpushsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinterest',
            name='surveyed_at',
            field=models.DateTimeField(blank=True, help_text='Set when the survey prompt is dismissed (any answer)', null=True),
        ),
    ]
