# Generated by Django 5.2.15 on 2026-06-20 14:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('destination', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('radius_km', models.FloatField(default=10)),
                ('delivery_date', models.DateField()),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_until', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
