# Generated by Django 6.0.6 on 2026-06-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryevent',
            name='route_corridor_km',
            field=models.FloatField(default=0, help_text="Optional narrower buffer along the straight-line route from the OPG to the destination (BlaBlaCar-style 'stops along the way'). 0 = off."),
        ),
    ]
