# Generated by Django 6.0.6 on 2026-06-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryevent_route_corridor_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryevent',
            name='route_corridor_km',
            field=models.FloatField(default=0, help_text="Optional narrower buffer along the straight-line route from the OPG to the destination (think 'stops along the way'). 0 = off."),
        ),
    ]
