# Generated by Django 5.2.15 on 2026-06-16 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_ready_from_alter_product_ready_until'),
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stands.stand'),
        ),
    ]
