# Generated by Django 5.2.15 on 2026-06-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('products', '0004_product_catalog_item_product_variety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='delivery.deliveryevent'),
        ),
    ]
