# Generated by Django 6.0.6 on 2026-06-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opg',
            name='iban',
            field=models.CharField(blank=True, help_text='Croatian IBAN for receiving payments (HR + 19 digits)', max_length=21),
        ),
    ]
