# Generated by Django 5.2.15 on 2026-06-14 10:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_parcel_is_active_alter_parcel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='area_sq_m',
            field=models.FloatField(blank=True, help_text='Area in square meters', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
