# Generated by Django 6.0.6 on 2026-06-30 19:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('opg', '0002_opg_iban'),
        ('parcels', '0003_alter_parcel_area_sq_m_alter_parcel_location'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_ratings_received', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('farmer', 'buyer')},
            },
        ),
        migrations.CreateModel(
            name='FieldInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surveyed_at', models.DateTimeField(blank=True, help_text='Set when the survey prompt is dismissed (any answer)', null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_interests', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='parcels.parcel')),
            ],
            options={
                'unique_together': {('buyer', 'parcel')},
            },
        ),
        migrations.CreateModel(
            name='OPGRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opg_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('opg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='opg.opg')),
            ],
            options={
                'unique_together': {('buyer', 'opg')},
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='catalog.productcatalog')),
                ('opg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='opg.opg')),
            ],
            options={
                'unique_together': {('buyer', 'opg', 'catalog_item')},
            },
        ),
    ]
