# Generated by Django 6.0.6 on 2026-06-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_email',
            field=models.EmailField(blank=True, help_text='Optional - if set, a receipt PDF is emailed here on confirmation', max_length=254),
        ),
    ]
