# Generated by Django 5.2.14 on 2026-06-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='delivery_radius_km',
            field=models.FloatField(default=0),
        ),
    ]
